#if !canImport(ObjectiveC)
import XCTest

extension BestHandsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BestHandsTests = [
        ("test_bestHand_bestFullHouse", test_bestHand_bestFullHouse),
        ("test_bestHand_bestHighest", test_bestHand_bestHighest),
        ("test_bestHand_bestPair", test_bestHand_bestPair),
        ("test_bestHand_bestThreeOfAKind", test_bestHand_bestThreeOfAKind),
        ("test_bestHand_bestTwoPair", test_bestHand_bestTwoPair),
        ("test_bestHand_fourOfAKind", test_bestHand_fourOfAKind),
        ("test_getBestPlayerHand_flushGotStraightAvailable", test_getBestPlayerHand_flushGotStraightAvailable),
        ("test_getBestPlayerHand_straightFlush", test_getBestPlayerHand_straightFlush),
    ]
}

extension DecideWinnerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DecideWinnerTests = [
        ("test_decideWinner_noBetsNoWinners", test_decideWinner_noBetsNoWinners),
        ("test_decideWinner_oneBetsOneWinners", test_decideWinner_oneBetsOneWinners),
    ]
}

extension PokerChallengeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PokerChallengeTests = [
        ("test_arrayGetOrdered", test_arrayGetOrdered),
        ("test_arrayGetOrderedHand_returns5HighestCards", test_arrayGetOrderedHand_returns5HighestCards),
        ("test_cards_returnsIfPlayerHasHand", test_cards_returnsIfPlayerHasHand),
        ("test_cards_returnsIfPlayerHasHandAndRiver", test_cards_returnsIfPlayerHasHandAndRiver),
        ("test_cards_returnsOnlyPassedRiver", test_cards_returnsOnlyPassedRiver),
        ("test_getAllPlayersWhoBetEnoughToPlay", test_getAllPlayersWhoBetEnoughToPlay),
        ("test_getAllPlayersWhoBetEnoughToPlay_bet0", test_getAllPlayersWhoBetEnoughToPlay_bet0),
        ("test_getAllPlayersWhoBetEnoughToPlay_everyonePlays", test_getAllPlayersWhoBetEnoughToPlay_everyonePlays),
        ("test_getFlush_returnsNilIfNoFlush", test_getFlush_returnsNilIfNoFlush),
        ("test_getFlush_returnsSuitIfFlush", test_getFlush_returnsSuitIfFlush),
        ("test_getFlushHand_returnsCardsIfFlushOrdered", test_getFlushHand_returnsCardsIfFlushOrdered),
        ("test_getFlushHand_returnsEmptyArrayIfNoFlush", test_getFlushHand_returnsEmptyArrayIfNoFlush),
        ("test_getFlushHand_returnsHighestFlush", test_getFlushHand_returnsHighestFlush),
        ("test_getFourOfAKind", test_getFourOfAKind),
        ("test_getFourOfAKind_HighestIsGotFromPlayer", test_getFourOfAKind_HighestIsGotFromPlayer),
        ("test_getFourOfAKind_HighestIsGotFromRiver", test_getFourOfAKind_HighestIsGotFromRiver),
        ("test_getFourOfAKind_NoFourOfAKind", test_getFourOfAKind_NoFourOfAKind),
        ("test_getFullHouse_8sAnd9s", test_getFullHouse_8sAnd9s),
        ("test_getFullHouse_emptyReturn", test_getFullHouse_emptyReturn),
        ("test_getFullHouse_fromRiver", test_getFullHouse_fromRiver),
        ("test_getStraightHand_2ndHighestCardStartsStraight", test_getStraightHand_2ndHighestCardStartsStraight),
        ("test_getStraightHand_highestCardIsInStraigh", test_getStraightHand_highestCardIsInStraigh),
        ("test_getStraightHand_NoStraight", test_getStraightHand_NoStraight),
        ("test_highestCard", test_highestCard),
        ("test_pair_fromHandAndRiverWithHighCard", test_pair_fromHandAndRiverWithHighCard),
        ("test_pair_fromHandWithHighCard", test_pair_fromHandWithHighCard),
        ("test_pair_fromRiverWithHighCard", test_pair_fromRiverWithHighCard),
        ("test_pair_noPair", test_pair_noPair),
        ("test_straightFlush_DoesntExist", test_straightFlush_DoesntExist),
        ("test_straightFlush_Exists", test_straightFlush_Exists),
        ("test_threeOfAKind", test_threeOfAKind),
        ("test_threeOfAKind_fromRiver_highFromHand", test_threeOfAKind_fromRiver_highFromHand),
        ("test_twoPair_fromRiver", test_twoPair_fromRiver),
        ("test_twoPair_threePossiblePairsTakesHighestTwo", test_twoPair_threePossiblePairsTakesHighestTwo),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BestHandsTests.__allTests__BestHandsTests),
        testCase(DecideWinnerTests.__allTests__DecideWinnerTests),
        testCase(PokerChallengeTests.__allTests__PokerChallengeTests),
    ]
}
#endif
