#if !canImport(ObjectiveC)
import XCTest

extension BestHandsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BestHandsTests = [
        ("test_bestHand_bestFullHouse", test_bestHand_bestFullHouse),
        ("test_bestHand_fourOfAKind", test_bestHand_fourOfAKind),
        ("test_getBestPlayerHand_flushGotStraightAvailable", test_getBestPlayerHand_flushGotStraightAvailable),
        ("test_getBestPlayerHand_straightFlush", test_getBestPlayerHand_straightFlush),
    ]
}

extension PokerChallengeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PokerChallengeTests = [
        ("test_arrayGetOrdered", test_arrayGetOrdered),
        ("test_arrayGetOrderedHand_returns5HighestCards", test_arrayGetOrderedHand_returns5HighestCards),
        ("test_cards_returnsIfPlayerHasHand", test_cards_returnsIfPlayerHasHand),
        ("test_cards_returnsIfPlayerHasHandAndRiver", test_cards_returnsIfPlayerHasHandAndRiver),
        ("test_cards_returnsOnlyPassedRiver", test_cards_returnsOnlyPassedRiver),
        ("test_getFlush_returnsNilIfNoFlush", test_getFlush_returnsNilIfNoFlush),
        ("test_getFlush_returnsSuitIfFlush", test_getFlush_returnsSuitIfFlush),
        ("test_getFlushHand_returnsCardsIfFlushOrdered", test_getFlushHand_returnsCardsIfFlushOrdered),
        ("test_getFlushHand_returnsEmptyArrayIfNoFlush", test_getFlushHand_returnsEmptyArrayIfNoFlush),
        ("test_getFlushHand_returnsHighestFlush", test_getFlushHand_returnsHighestFlush),
        ("test_getFourOfAKind", test_getFourOfAKind),
        ("test_getFourOfAKind_HighestIsGotFromPlayer", test_getFourOfAKind_HighestIsGotFromPlayer),
        ("test_getFourOfAKind_HighestIsGotFromRiver", test_getFourOfAKind_HighestIsGotFromRiver),
        ("test_getFourOfAKind_NoFourOfAKind", test_getFourOfAKind_NoFourOfAKind),
        ("test_getFullHouse_8sAnd9s", test_getFullHouse_8sAnd9s),
        ("test_getFullHouse_emptyReturn", test_getFullHouse_emptyReturn),
        ("test_getFullHouse_fromRiver", test_getFullHouse_fromRiver),
        ("test_getStraightHand_2ndHighestCardStartsStraight", test_getStraightHand_2ndHighestCardStartsStraight),
        ("test_getStraightHand_highestCardIsInStraigh", test_getStraightHand_highestCardIsInStraigh),
        ("test_getStraightHand_NoStraight", test_getStraightHand_NoStraight),
        ("test_straightFlush_DoesntExist", test_straightFlush_DoesntExist),
        ("test_straightFlush_Exists", test_straightFlush_Exists),
        ("test_threeOfAKind", test_threeOfAKind),
        ("test_threeOfAKind_fromRiver_highFromHand", test_threeOfAKind_fromRiver_highFromHand),
    ]

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(BestHandsTests.__allTests__BestHandsTests),
            testCase(PokerChallengeTests.__allTests__PokerChallengeTests),
        ]
    }
}
#endif
